---
title: "LiDAR toolbox learning summary"
author: "Jing-Zhong Lu"
date: "2025-06-14"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## las2
data using as an example to summarise course codes
```{r}
las2 <- readLAS("las_area2.laz")
plot(las2, bg="white", color="Classification")
```

## DTM: digital terrain model
```{r}
ground2 <- filter_ground(las2)
plot(ground2)

dtm_tin2 <- rasterize_terrain(las2, res=1, algorithm = tin())
plot(dtm_tin2)
plot_dtm3d(dtm_tin2)

# export to QGIS
raster::writeRaster(dtm_tin2, "Data/dtm_tin2.tiff")
```

## Pointclound normalization
```{r}
nlas_right2 <- normalize_height(las2, tin())
plot(las2)
plot(nlas_right2)
nlas_right2@data$Z %>% summary
nlas_right2@data$Z %>% sort %>% tail(., n=20)

# final_filter
nlas_right_filtered2 <- filter_poi(nlas_right2, Z > 0, Z < 40)
plot(nlas_right_filtered2, legend=TRUE)

# canopy height model
chm_right2 <- rasterize_canopy(nlas_right_filtered2, res=1, algorithm = dsmtin())
plot(chm_right)

writeRaster(chm_right, "Data/chm_right.tiff")
```

## DSM: digital surface model
```{r}
dsm2 <- rasterize_canopy(las2, res=1, algorithm = dsmtin())
plot(dsm2)
plot_dtm3d(dsm2)
```

## tree detection
```{r}
tree_top_5 <- locate_trees(nlas_right_filtered2, lmf(ws = 5)) # better use the nlas (normalised) rather than the las
# tree detection with local maximum filter LMF
# windows 5 x 5 m
tree_top_5
plot(tree_top_5)
sf::st_write(tree_top_5, "Data/las2_tree_top_5.shp", layer_options = "SHPT=POINTZ")


# a function to decide 
f <- function(x) {x * 0.1 + 3} #create a function that makes a mw that increase from 3 (whan height is 0) and increase of 0.1 for each meter. you can change the 0.1 and increas eto 0.2...
heights <- seq(0,40,5)
ws <- f(heights)
plot(heights, ws, type = "l", ylim = c(0,6))

tree_top_function_right2 <- locate_trees(nlas_right_filtered2, lmf(f)) # the function adjust the ws based on tree heights
st_write(tree_top_function_right2, "Data/las2_tree_top_function.shp", delete_layer = TRUE, layer_options = "SHPT=POINTZ")
```


## tree segmentation
```{r}
# @Dalponte2016: CHM + function to detect tree tops
# @Li2012: No CHM needed - 3D geometric clustering
algorithms1 <- dalponte2016(chm_right2, tree_top_function_right2)
trees_segmented_dalponte2 <- segment_trees(nlas_right_filtered2, algorithms1)
plot(trees_segmented_dalponte2, color="treeID")

plot(trees_segmented_dalponte2@data$X, trees_segmented_dalponte2@data$Y, col=trees_segmented_dalponte2@data$treeID)

# selecting one single tree
tree1 <- filter_poi(trees_segmented_dalponte2, treeID==120)
plot(tree1)

#Li2012
algorithms2 <- li2012()
trees_segmented_li2012.2 <- segment_trees(nlas_right_filtered2, algorithms2)
plot(trees_segmented_li2012.2, color="treeID")
```


## crown metric and shape
```{r}
crown_dalponte2 <- crown_metrics(trees_segmented_dalponte2, func = .stdtreemetrics, geom = "convex")

# convex: more linear; concave: more rough
st_write(crown_dalponte2, "Data/las2_crown_dalponte.shp")
# cnvhll is the area of the crown in meter2

crown_dalponte_all_metrics2 <- crown_metrics(trees_segmented_dalponte2, func = .stdmetrics_z, geom = "convex")

# all metrics are extracted
crown_dalponte_all_metrics2
# zmax: highest point
# z: refers to the elevation
# i: intensity
# rn: return number
# q: quantile
# a: ScanAngleRank or ScanAngle
# n: count
# p: percentage
# random forests can be powerful to classify images
```


```{r}
# get information from a single point
# tree level matrix 
# a new shp file has to be created for las2 data
test_points <- st_read("Data/punctual_plot.shp")
metric_plot <- plot_metrics(nlas_right_filtered, func = .stdmetrics_z, radius=20, test_points)

# volume
crown_dalponte_new <- crown_metrics(trees_segmented_dalponte2, func = .stdmetrics_z, geom="concave")
plot(crown_dalponte_new)

crown_dalponte_new$volume <- 0.5*(crown_dalponte_new$zmax^2.5)/100 

# use with caution! 
# Some sources suggest values between .03 and .07 depending on species.
plot(crown_dalponte_new)
plot(crown_dalponte_new["volume"])

# volume at pixel level
crown_dalponte_new <- pixel_metrics(trees_segmented_dalponte2, func = .stdmetrics_z, 5) # 5 meter resolution
crown_dalponte_new$volume <- .5*(crown_dalponte_new$zmax^2.5)/100
plot(crown_dalponte_new)
plot(crown_dalponte_new["volume"])
```

